### ISSUE TITLE
Checkbox in objective for brainhack

### ISSUE THREAD

**Issue by mathdugre** [mtl-brainhack-school-2019/Anthony-Gifuni-repo#3]
It would be nice to add checked box to know what is done

For example:
- [x] Organize my data set into the BIDS format.
- [ ] Start running fMRIprep on the sample using Compute Canada Resources.
- [ ] ...

**Comment by CTanguay-Sabourin** [comment]
- [ ]

**Comment by mathdugre** [comment]
To make the checked box do:
```
- [ ] unchecked box
- [x] checked box
```
